env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = HYPRSHOT_DIR,/home/dipkiran/Pictures/Screenshots

monitor = eDP-1,1920x1080@60,0x0,1
gesture = 3, horizontal, workspace
workspace = 2, monitor:eDP-1, default:true

exec-once = uwsm app -- waybar
exec-once = uwsm app -- hypridle

source = ~/.config/hypr/conf.d/animations.conf
source = ~/.config/hypr/conf.d/decoration.conf
source = ~/.config/hypr/conf.d/general.conf
source = ~/.config/hypr/conf.d/keybinds.conf
source = ~/.config/hypr/conf.d/windowrules.conf
