general {
  hide_cursor = true
  ignore_empty_input = true
}

background {
  monitor = eDP-1
  blur_passes = 2
  blur_size = 2
  path = ~/.config/hypr/wallpaper.png
}

label {
  monitor = eDP-1
  text = $TIME
  color = rgb(d8cab8)
  font_size = 120
  font_family = FiraCode Nerd Font Bold
  position = 0, -100
  valign = top
}

label {
  monitor = eDP-1
  text = care for a shower?
  color = rgb(d8cab8)
  font_size = 48
  position = 0, 100
  font_family = FiraCode Nerd Font
}

input-field {
  monitor = eDP-1
  size = 250, 50
  fade_timeout = 5000
  outline_thickness = 1
  inner_color = rgba(00000000)
  outer_color = rgb(d8cab8)
  font_color = rgb(d8cab8)
  placeholder_text = whats my name?
  fail_text = you dont remember me?
  fail_color = rgb(d8cab8)
  check_color = rgb(d8cab8)
  position = 0, 100
  valign = bottom
}
