dwindle {
  pseudotile = true
  preserve_split = true
}

master {
  new_status = master
}

misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
}

input {
  accel_profile = adaptive
  sensitivity = 0.5

  touchpad {
    natural_scroll = true
  }
}
